## **Load data**

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
%pwd
%cd 'gdrive/My Drive/bladder cancer'
%ls

/content/gdrive/My Drive/bladder cancer
'Baseline ECOG Score.png'  'tree_Baseline ECOG Score.dot'
'Immune phenotype.png'     'tree_Baseline ECOG Score.png'
 IMvigor210_clin.csv       'tree_Immune phenotype.dot'
 imvigor210.csv            'tree_Immune phenotype.png'
 IMvigor210.xlsx            tree_Sex.dot
 Race.png                   tree_Sex.png
'TCGA Subtype.dot'         'tree_TCGA Subtype.png'
 tmm.csv


In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# xlsx = pd.read_excel('./IMvigor210.xlsx', sheet_name = 'TMM norm' )
# xlsx.to_csv('./tmm.csv',index=False)
# print(xlsx.columns)
%ls

'Baseline ECOG Score.png'  'tree_Baseline ECOG Score.dot'
'Immune phenotype.png'     'tree_Baseline ECOG Score.png'
 IMvigor210_clin.csv       'tree_Immune phenotype.dot'
 imvigor210.csv            'tree_Immune phenotype.png'
 IMvigor210.xlsx            tree_Sex.dot
 Race.png                   tree_Sex.png
'TCGA Subtype.dot'         'tree_TCGA Subtype.png'
 tmm.csv


In [5]:
data = pd.read_csv("IMvigor210_clin.csv")
print(data.columns)
print(len(data))

Index(['SampleID', 'Best Confirmed Overall Response', 'binaryResponse',
       'Enrollment IC', 'IC Level', 'TC Level', 'Immune phenotype',
       'FMOne mutation burden per MB', 'Sex', 'Race',
       'Intravesical BCG administered', 'Baseline ECOG Score',
       'Tobacco Use History', 'Met Disease Status', 'Sample age', 'Tissue',
       'Received platinum', 'Sample collected pre-platinum',
       'Neoantigen burden per MB', 'sizeFactor', 'ANONPT_ID', 'os', 'censOS',
       'Lund', 'Lund2', 'TCGA Subtype'],
      dtype='object')
348


In [6]:
marker = pd.read_csv("tmm.csv")
ori_marker = marker 

In [7]:
marker.columns

Index(['Entrez Gene ID', 'Symbol', 'SAMf2ce197162ce', 'SAM698d8d76b934',
       'SAMc1b27bc16435', 'SAM85e41e7f33f9', 'SAMf275eb859a39',
       'SAM7f0d9cc7f001', 'SAM4305ab968b90', 'SAMcf018fee2acd',
       ...
       'SAMe7e4f7c076a7', 'SAMbe25e2c88f3e', 'SAM4caabd64e7fd',
       'SAMc6eff056c89a', 'SAM5cfa1699bdb7', 'SAMda4d892fddc8',
       'SAM3a1c9632ff7b', 'SAM8b4b8b0f9e73', 'SAMe3d4266775a9',
       'SAM2de7cffb5f72'],
      dtype='object', length=350)

## **Data Preprocessing**

In [8]:
marker = marker.rename(columns = {'Symbol':'SampleID'}) 
marker = marker.drop(['Entrez Gene ID'], axis = 1).T
marker.columns = marker.iloc[0]
marker = marker.drop(marker.index[0])

In [9]:
print(marker.head())

SampleID            A1BG      ADA     CDH2  ...    DGCR2 CASP8AP2     SCO2
SAMf2ce197162ce  3.97148  10.2378  9.12886  ...  9.76685  11.1387  10.2317
SAM698d8d76b934  6.19179  10.3348  13.7274  ...   9.8475  11.4952  10.4029
SAMc1b27bc16435  3.56082   9.1993  5.63238  ...   9.9633  10.9028  9.24281
SAM85e41e7f33f9  3.88137  11.7038  9.27618  ...  9.56163     11.8  11.1349
SAMf275eb859a39  4.90625  10.1602  7.49974  ...  10.2516   11.416  10.5975

[5 rows x 17692 columns]


In [10]:
len(marker), len(marker.columns)

(348, 17692)

In [11]:
target_column = 'Immune phenotype'

In [12]:
## match non-digit labels to digits

# data['Best Confirmed Overall Response'] = data['Best Confirmed Overall Response'].map({'CR':0, 'PR':1, 'SD':2, 'PD':3, 'NE':4})
# data['Enrollment IC'] = data['Enrollment IC'].map({'IC0':0, 'IC1':1, 'IC2':2})

# NA = -1 -> nan 빼고 해보기
data['Immune phenotype'] = data['Immune phenotype'].map({'desert':0, 'inflamed':1, 'excluded':2})

# data['Sex'] = data['Sex'].map({'M':0, 'F':1})
# # NA = -1, rm 'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER' since the number of it is 1
# data['Race'] = data['Race'].map({'BLACK OF AFRICAN AMERICAN':0, 'ASIAN':1, 'WHITE':2,  'OTHER':4})
# data['Race'] = data['Race'].fillna(-1)
# data['Intravesical BCG administered'] = data['Intravesical BCG administered'].map({'N':0, 'Y':1})
# data['Tobacco Use History'] = data['Tobacco Use History'].map({'NEVER':0, 'PREVIOUS':1, 'CURRENT':2})

# # # replace NA to the mean of N, Y
# # data['Met Disease Status'] = data['Met Disease Status'].map({'Liver':0, 'Visceral':1, 'LN Only':2, 'NA': -1})
# data['Sample age'] = data['Sample age'].map({'(less than) 1 year':0, '1-2 years':1, 'more than 2 years':2})
# data['Received platinum'] = data['Received platinum'].map({'N':0, 'Y':1})

# # replace NA to the mean of N, Y
# #data['Sample collected pre-platinum'] = data['Sample collected pre-platinum'].map({'N':0, 'Y':1, 'NA': 0.5})
# data['Lund'] = data['Lund'].map({'MS1a':0, 'MS1b':1, 'MS2a1':2,'MS2a2':3, 'MS2b1':4, 'MS2b2.1':5, 'MS2b2.2':6})
# data['Lund2'] = data['Lund2'].map({'UroA':0, 'UroB':1, 'Genomically unstable':3, 'Infiltrated':4, 'Basal/SCC-like':5})
# data['TCGA Subtype'] = data['TCGA Subtype'].map({'I':0, 'II':1, 'III':2, 'IV':3})     

# # replace NA to the mean of column 
# data['Neoantigen burden per MB'] = data['Neoantigen burden per MB'].fillna(data.mean()['Neoantigen burden per MB'])
# # replace NA to the mean of column 
# data['FMOne mutation burden per MB'] = data['FMOne mutation burden per MB'].fillna(data.mean()['FMOne mutation burden per MB'])

  

print(data[target_column])


0      NaN
1      2.0
2      2.0
3      1.0
4      2.0
      ... 
343    NaN
344    NaN
345    2.0
346    NaN
347    NaN
Name: Immune phenotype, Length: 348, dtype: float64


In [13]:
if target_column in marker.columns:
  marker = marker.drop(target_column, axis = 1)

In [14]:
data.index = data['SampleID']
marker.index.equals(data.index)

True

In [15]:
marker = marker.join(data[target_column])
marker = marker.reset_index()
marker = marker.rename(columns = {'index':'SampleID'}) 
marker.head()

SampleID     A1BG      ADA  ... CASP8AP2     SCO2 Immune phenotype
0  SAMf2ce197162ce  3.97148  10.2378  ...  11.1387  10.2317              NaN
1  SAM698d8d76b934  6.19179  10.3348  ...  11.4952  10.4029              2.0
2  SAMc1b27bc16435  3.56082   9.1993  ...  10.9028  9.24281              2.0
3  SAM85e41e7f33f9  3.88137  11.7038  ...     11.8  11.1349              1.0
4  SAMf275eb859a39  4.90625  10.1602  ...   11.416  10.5975              2.0

[5 rows x 17694 columns]

In [16]:
marker.index

RangeIndex(start=0, stop=348, step=1)

In [17]:
marker = marker.dropna(axis=0)
marker.shape

(284, 17694)

In [18]:
marker.reset_index(inplace=True, drop=True)
marker.index

RangeIndex(start=0, stop=284, step=1)

In [19]:
######17694 check
marker.shape

(284, 17694)

In [20]:
# split train and test data
# 5-fold cross validation

train_list = []
test_list = []

from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=5, shuffle=False, random_state=1004)

for train_idx, test_idx in fold.split(marker, marker[target_column]):
    # print("TRAIN:", train_idx, "\nTEST:", test_idx)
    train_list.append(marker.loc[train_idx])
    test_list.append(marker.loc[test_idx])

print(len(train_list), len(test_list))

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


5 5


In [21]:
# groupby 1 df

print(train_list[0].groupby(target_column).size())
print(test_list[0].groupby(target_column).size()) 

Immune phenotype
0.0     61
1.0     59
2.0    107
dtype: int64
Immune phenotype
0.0    15
1.0    15
2.0    27
dtype: int64


In [22]:
# check the average number of total 5 training data per class
total_train = pd.concat([train_list[0], train_list[1], train_list[2], train_list[3], train_list[4]], axis=0, ignore_index=True)
print(total_train.groupby(target_column).size())
print('\n', total_train.groupby(target_column).size()/5)

Immune phenotype
0.0    304
1.0    296
2.0    536
dtype: int64

 Immune phenotype
0.0     60.8
1.0     59.2
2.0    107.2
dtype: float64


In [23]:
# check the average number of total 5 test data per class
total_test = pd.concat([test_list[0], test_list[1], test_list[2], test_list[3], test_list[4]], axis=0, ignore_index=True)
print(total_test.groupby(target_column).size())
print('\n', total_test.groupby(target_column).size()/5)

Immune phenotype
0.0     76
1.0     74
2.0    134
dtype: int64

 Immune phenotype
0.0    15.2
1.0    14.8
2.0    26.8
dtype: float64


In [24]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()

In [25]:
x_train_list, x_test_list, y_train_list, y_test_list = [], [], [], []
decoded_y_train_list, decoded_y_test_list = [], []

In [26]:
for (train, test) in zip(train_list, test_list): 
  decoded_y_train = train[target_column]
  Y = encoder.fit_transform(decoded_y_train)
  y_train = pd.get_dummies(Y).values

  decoded_y_test = test[target_column]
  Y = encoder.fit_transform(decoded_y_test)
  y_test = pd.get_dummies(Y).values

  x_train = train.drop([target_column], axis = 1)
  x_test = test.drop([target_column], axis = 1)

  features = marker.columns.tolist()
  features.remove(target_column)
  features.remove('SampleID')

  x_train.set_index(x_train['SampleID'], inplace=True, drop=True)
  x_test.set_index(x_test['SampleID'], inplace=True, drop=True)

  x_train.drop(['SampleID'], axis=1, inplace=True)
  x_test.drop(['SampleID'], axis=1, inplace=True)
  x_train.reset_index(drop=True, inplace=True)
  x_test.reset_index(drop=True, inplace=True)

  x_test = np.asarray(x_test).astype(np.float32)
  x_train = np.asarray(x_train).astype(np.float32)

  x_train_list.append(x_train)
  x_test_list.append(x_test)
  y_train_list.append(y_train)
  y_test_list.append(y_test)
  decoded_y_train_list.append(decoded_y_train)
  decoded_y_test_list.append(decoded_y_test)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3997: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


In [27]:
from keras import backend as K
import tensorflow as tf

def result(one_pred, y_test):
  acc, rec, pre = [], [], []
  
  """total Accuracy"""
  total_acc = K.sum(one_pred[:,:] * y_test[:,:])/y_test.shape[0]

  for target_class in range(y_test.shape[1]):
    """RECALL per class"""

    tp = K.sum(one_pred[:, target_class] * y_test[:, target_class])  #dtype=float32
    tpfn = tf.cast(K.sum(y_test[:, target_class]), tf.float32)  #uint8 to float32

    # Recall =  (True Positive) / (True Positive + False Negative)
    recall = tp / (tpfn + K.epsilon())

    """PRECISION per class"""

    tpfp = tf.cast(K.sum(one_pred[:, target_class]), tf.float32)

    # Precision = (True Positive) / (True Positive + False Positive)
    precision = tp / (tpfp + K.epsilon())

    """Accuracy per class"""
    tn = np.sum((one_pred[:, target_class]==0) * (y_test[:, target_class]==0).T)

    accuracy = (tp + tn)/(tpfn + tpfp - tp + tn)

    acc.append(accuracy)
    rec.append(recall)
    pre.append(precision)

    print("\nclass: ", target_class)
    print("tp: ", tp)
    print("tp+fn: ", tpfn)
    print("tp+fp: ", tpfp)

    tf.print("Accuracy = {:.3f}".format(accuracy))
    tf.print("Recall = {:.3f}".format(recall))
    tf.print("Precision = {:.3f} ".format(precision))

  return acc, rec, pre, total_acc

# **Neural Networks**

In [39]:
one_pred_list = []

In [40]:
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
from keras import regularizers
from keras.callbacks import EarlyStopping
%matplotlib inline

# EarlyStopping = EarlyStopping(monitor='val_loss', patience=20)

for (x_train, x_test, y_train, y_test) in zip(x_train_list, x_test_list, y_train_list, y_test_list):
  model = Sequential()

  model.add(Dense(y_train.shape[1], input_shape=(len(features),), activation='softmax'))

  opt = Adam(learning_rate=0.00001)
  model.compile(loss='categorical_crossentropy', 
                optimizer=opt, 
                metrics=['accuracy']) 


  # model.summary()

  hist = model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=500, verbose=0)

  # plt.figure(figsize=(12,8))
  # plt.plot(hist.history['loss'])
  # plt.plot(hist.history['val_loss'])
  # plt.plot(hist.history['accuracy'])
  # plt.plot(hist.history['val_accuracy'])
  # plt.legend(['loss','val_loss', 'acc','val_acc'])
  # plt.grid()
  # plt.show()

  loss, accuracy = model.evaluate(x_test, y_test)
  print("Accuracy = {:.3f}".format(accuracy))

  prediction = model.predict(x_test, verbose=1)
  one_pred = np.zeros_like(prediction)
  # one hot encoding of prediction
  one_pred[np.arange(len(prediction)), prediction.argmax(1)] = 1
  one_pred_list.append(one_pred)

2/2 [==============================] - 0s 7ms/step - loss: 1.4269 - accuracy: 0.5614
Accuracy = 0.561
2/2 [==============================] - 0s 3ms/step - loss: 1.0851 - accuracy: 0.5263
Accuracy = 0.526
2/2 [==============================] - 0s 3ms/step - loss: 1.1649 - accuracy: 0.5614
Accuracy = 0.561
2/2 [==============================] - 0s 3ms/step - loss: 1.1063 - accuracy: 0.5439
Accuracy = 0.544
2/2 [==============================] - 0s 3ms/step - loss: 1.2513 - accuracy: 0.5536
Accuracy = 0.554
2/2 [==============================] - 0s 3ms/step


In [41]:
acc_list, rec_list, pre_list, total_acc_list = [], [], [], []

for one_pred, y_test in zip(one_pred_list, y_test_list):
  acc, rec, pre, total_acc = result(one_pred, y_test)
  acc_list.append(acc)
  rec_list.append(rec)
  pre_list.append(pre)
  total_acc_list.append(total_acc)


class:  0
tp:  tf.Tensor(5.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(15.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(10.0, shape=(), dtype=float32)
Accuracy = 0.737
Recall = 0.333
Precision = 0.500 

class:  1
tp:  tf.Tensor(4.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(15.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(6.0, shape=(), dtype=float32)
Accuracy = 0.772
Recall = 0.267
Precision = 0.667 

class:  2
tp:  tf.Tensor(23.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(27.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(41.0, shape=(), dtype=float32)
Accuracy = 0.614
Recall = 0.852
Precision = 0.561 

class:  0
tp:  tf.Tensor(9.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(15.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(19.0, shape=(), dtype=float32)
Accuracy = 0.719
Recall = 0.600
Precision = 0.474 

class:  1
tp:  tf.Tensor(5.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(15.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(7.0, shape=(), dtype=float32)
Accuracy = 0.789
Recall = 0

In [42]:
# total accuracy
total_acc_list

[<tf.Tensor: shape=(), dtype=float32, numpy=0.5614035>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5263158>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5614035>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.54385966>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.5535714>]

In [43]:
tf.print("Total Accuracy = {:.3f}".format(K.sum(total_acc_list)/len(total_acc_list)))

Total Accuracy = 0.549


In [44]:
# decode one hot vector
y_pred = np.argmax(one_pred, axis=1).reshape(-1, 1)
# y_pred

In [45]:
from sklearn import metrics

for one_pred, y_test in zip(one_pred_list, y_test_list):
  
  dec_y_pred = np.argmax(one_pred, axis=1).reshape(-1, 1)
  dec_y_test = np.argmax(y_test, axis=1).reshape(-1, 1)

  # Print the confusion matrix
  # print(metrics.confusion_matrix(dec_y_test, dec_y_pred))

  # Print the precision and recall, among other metrics
  print(metrics.classification_report(dec_y_test, dec_y_pred, digits=3))

              precision    recall  f1-score   support

           0      0.500     0.333     0.400        15
           1      0.667     0.267     0.381        15
           2      0.561     0.852     0.676        27

    accuracy                          0.561        57
   macro avg      0.576     0.484     0.486        57
weighted avg      0.573     0.561     0.526        57

              precision    recall  f1-score   support

           0      0.474     0.600     0.529        15
           1      0.714     0.333     0.455        15
           2      0.516     0.593     0.552        27

    accuracy                          0.526        57
   macro avg      0.568     0.509     0.512        57
weighted avg      0.557     0.526     0.520        57

              precision    recall  f1-score   support

           0      0.643     0.600     0.621        15
           1      0.500     0.533     0.516        15
           2      0.556     0.556     0.556        27

    accuracy        

In [46]:
# number of class
for i in range(y_test_list[0].shape[1]):
  acc_mean, rec_mean, pre_mean = 0, 0, 0
  
  # k-fold
  for j in range(len(acc_list)):  
    acc_mean += acc_list[j][i]
    rec_mean += rec_list[j][i]
    pre_mean += pre_list[j][i]
  
  acc_mean /= len(acc_list)
  rec_mean /= len(rec_list)
  pre_mean /= len(pre_list)

  print("\nclass: ", i)
  # mean score of k-folds
  tf.print("Accuracy = {:.3f}".format(acc_mean))
  tf.print("Recall = {:.3f}".format(rec_mean))
  tf.print("Precision = {:.3f} ".format(pre_mean))


class:  0
Accuracy = 0.757
Recall = 0.451
Precision = 0.554 

class:  1
Accuracy = 0.760
Recall = 0.390
Precision = 0.625 

class:  2
Accuracy = 0.581
Recall = 0.693
Precision = 0.544 


In [47]:
len(acc_list)

5

# **SVM**

In [48]:
acc_list, rec_list, pre_list, total_acc_list = [], [], [], []

In [49]:
# Support Vector Classifier
# one vs rest

from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier

for x_train, decoded_y_train, x_test, y_test in zip(x_train_list, decoded_y_train_list, x_test_list, y_test_list):
  svm = OneVsRestClassifier(SVC()).fit(x_train, decoded_y_train)
  y_pred_svc = svm.predict(x_test)

  # print(y_pred_svc)

  # encode y_pred_svc to one-hot vector 
  Y = encoder.fit_transform(y_pred_svc)
  y_pred_svc = pd.get_dummies(Y).values.astype(np.float32)

  acc, rec, pre, total_acc = result(y_pred_svc, y_test)
  acc_list.append(acc)
  rec_list.append(rec)
  pre_list.append(pre)
  total_acc_list.append(total_acc)


class:  0
tp:  tf.Tensor(7.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(15.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(9.0, shape=(), dtype=float32)
Accuracy = 0.825
Recall = 0.467
Precision = 0.778 

class:  1
tp:  tf.Tensor(4.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(15.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(4.0, shape=(), dtype=float32)
Accuracy = 0.807
Recall = 0.267
Precision = 1.000 

class:  2
tp:  tf.Tensor(25.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(27.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(44.0, shape=(), dtype=float32)
Accuracy = 0.632
Recall = 0.926
Precision = 0.568 

class:  0
tp:  tf.Tensor(6.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(15.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(8.0, shape=(), dtype=float32)
Accuracy = 0.807
Recall = 0.400
Precision = 0.750 

class:  1
tp:  tf.Tensor(2.0, shape=(), dtype=float32)
tp+fn:  tf.Tensor(15.0, shape=(), dtype=float32)
tp+fp:  tf.Tensor(3.0, shape=(), dtype=float32)
Accuracy = 0.754
Recall = 0.1

In [50]:
tf.print("Total Accuracy = {:.3f}".format(K.sum(total_acc_list)/len(total_acc_list)))

Total Accuracy = 0.606


In [51]:
# number of class
for i in range(y_test_list[0].shape[1]):
  acc_mean, rec_mean, pre_mean = 0, 0, 0
  
  # k-fold
  for j in range(len(acc_list)):  
    acc_mean += acc_list[j][i]
    rec_mean += rec_list[j][i]
    pre_mean += pre_list[j][i]
  
  acc_mean /= len(acc_list)
  rec_mean /= len(rec_list)
  pre_mean /= len(pre_list)

  print("\nclass: ", i)
  # mean score of k-folds
  tf.print("Accuracy = {:.3f}".format(acc_mean))
  tf.print("Recall = {:.3f}".format(rec_mean))
  tf.print("Precision = {:.3f} ".format(pre_mean))


class:  0
Accuracy = 0.813
Recall = 0.409
Precision = 0.799 

class:  1
Accuracy = 0.789
Recall = 0.255
Precision = 0.792 

class:  2
Accuracy = 0.609
Recall = 0.911
Precision = 0.553 


In [52]:
# output개수가 0인 class가 있을 때 add [0]*y_pred_svc.shape[0]

# new_column = [0] * y_pred_svc.shape[0]
# y_pred_svc = np.insert(y_pred_svc, 2, new_column, axis=1)
# y_pred_svc